volumes:
    web_data:
        driver: local
        driver_opts:
            type: none
            device: /home/lzipp/data/web # For Linux
            # device: /Users/lzipp/Desktop/web_vol # For MacOS
            o: bind
    db_data:
        driver: local
        driver_opts:
            type: none
            device: /home/lzipp/data/db # For Linux
            # device: /Users/lzipp/Desktop/db_vol # For MacOS
            o: bind

networks:
    inception:
        name: inception
        driver: bridge

secrets:
    wp_db_root_pwd:
        file: ../secrets/wp_db_root_pwd.txt
    wp_admin_pwd:
        file: ../secrets/wp_admin_pwd.txt
    wp_db_user_pwd:
        file: ../secrets/wp_db_user_pwd.txt
    wp_user_pwd:
        file: ../secrets/wp_user_pwd.txt

services:
    nginx:
        container_name: nginx
        build:
            context: requirements/nginx
        ports:
            - "443:443"
        depends_on:
            - wordpress
            - db
        volumes:
            - web_data:/var/www/html
        networks:
            - inception
        secrets:
            - wp_db_root_pwd
            - wp_db_user_pwd
            - wp_admin_pwd
            - wp_user_pwd
        env_file: ".env"
        restart: always

    wordpress:
        container_name: wordpress
        build:
            context: requirements/wordpress
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - web_data:/var/www/html/
        networks:
            - inception
        secrets:
            - wp_db_root_pwd
            - wp_db_user_pwd
            - wp_admin_pwd
            - wp_user_pwd
        env_file: ".env"
        restart: unless-stopped

    db:
        container_name: db
        build:
            context: requirements/mariadb
        volumes:
            - db_data:/var/lib/mysql
        secrets:
            - wp_db_root_pwd
            - wp_db_user_pwd
            - wp_admin_pwd
            - wp_user_pwd
        env_file: ".env"
        networks:
            - inception
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
