volumes:
    wp_data:
        driver: local
    db_data:
        driver: local
    wordpress_website_files:
        driver: local

networks:
    inception:
        name: inception
        driver: bridge

secrets:
    db_root_pwd:
        file: src/secrets/db_root_pwd.txt
    wp_db_user_pwd:
        file: src/secrets/wp_db_user_pwd.txt
    wp_admin_pwd:
        file: src/secrets/wp_admin_pwd.txt
    wp_user_pwd:
        file: src/secrets/wp_user_pwd.txt

services:
    nginx:
        container_name: nginx
        build:
            context: src/requirements/nginx
        ports:
            - "443:443"
            - "80:80"
        depends_on:
            - wordpress
            - db
        volumes:
            - ./web:/var/www/html
        networks:
            - inception
        restart: always

    wordpress:
        container_name: wordpress
        build:
            context: src/requirements/wordpress
        depends_on:
            - db
        volumes:
            - wp_data:/var/www/html/
        networks:
            - inception
        secrets:
            - wp_admin_pwd
            - wp_user_pwd
            - wp_db_user_pwd
        environment:
            - WP_DB_NAME=${WP_DB_NAME}
            - WP_DB_USER=${WP_DB_USER}
            - WP_DB_HOST=${WP_DB_HOST}
            - WP_DB_PREFIX=${WP_DB_PREFIX}
            - WP_DOMAIN=${WP_DOMAIN}
            - WP_TITLE=${WP_TITLE}
            - WP_ADMIN=${WP_ADMIN}
            - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
            - WP_USER=${WP_USER}
            - WP_USER_EMAIL=${WP_USER_EMAIL}
        restart: unless-stopped

    db:
        container_name: db
        build:
            context: src/requirements/mariadb
        volumes:
            - db_data:/var/lib/mysql
        secrets:
            - wp_db_user_pwd
            - db_root_pwd
        environment:
            - WP_DB_USER=${WP_DB_USER}
            - WP_DB_NAME=${WP_DB_NAME}
        networks:
            - inception
        restart: unless-stopped
